### ISSUE TITLE
【bug】why Zotfile think purple is blue...

### ISSUE THREAD

**Issue by Darkluna999** [jlegewie/zotfile#601] opened 2022-04-08 10:48 UTC
when use purple annotation in the reader which is provided by Zotro6, I get the {{%color}} is blue
Even though zotero's built-in color is ARGB , it shouldn't deviate so much
Or how can I customize the color map when I make `extensions.zotfile.pdfExtraction.colorNotes` is `true` ?

**Comment by Servinjesus1** [comment] 2022-05-18 17:08
Was going to say just add the Zotero purple (`a28ae5`) to `extensions.zotfile.pdfExtraction.colorCategories` and see if that works, but it's not working for me. Instead, Magenta commandeers any purple I try to define. I tried defining multiple purples and that didn't work either.

But, two questions: can you still see a button to extract annotations in Zotero 6? I'm having #605 issues. Also, Zotero 6 doesn't save annotations to PDFs, but to their database. Are you trying to extract straight from the PDF after annotating it in Zotero 6, or Exporting the PDF, reimporting it into your library, then extracting with Zotfile?

**Comment by Darkluna999** [comment] 2022-05-18 17:11
just with zotilo，you can set a hotkey for it

**Comment by Servinjesus1** [comment] 2022-05-18 17:41
Ah, thanks - looks like a [Zutilo bug](https://github.com/wshanks/Zutilo/issues/228), sorry for going off-topic. Can you post a minimum working example (MWE) of instructions to reproduce your bug? Let me know what happens after you update your `colorCategories`, too.

**Comment by Darkluna999** [comment] 2022-05-18 17:45
I'm afraid that I can't. It has been uninstalled from my Zotero for a long time....

**Comment by Servinjesus1** [comment] 2022-05-18 18:57
Ok, can you close this bug? I am going to open a new one for my own report.

**Closed** 2022-05-18 18:58 UTC
