### ISSUE TITLE
Use logical page numbers (if available) for reference extraced pdf annotations

### ISSUE THREAD

**Issue by andersjohansson** [jlegewie/zotfile#57] opened 2013-01-09 19:51 UTC
A lot of pdf's from academic databases (eg. JSTOR) uses so called "logical page numbers" (at the same time a lot of databases add a cover page to articles, making the page computed from `pages-field + page number in pdf` wrong). This is true also of many pdf e-books.
It would be great if the annotation extraction could use the logical page numbers (if they exist) and then fall back to the older solution. This of course depends on whether this is supported in the backends, but shouldn't be too difficult to implement in that case. I might take a look at it myself.

Thanks for a great addon by the way!

**Comment by jlegewie** [comment] 2016-04-05 14:05
Closing this as duplicate of #190

**Closed by jlegewie** 2016-04-05 14:05 UTC
Labels: enhancement, pdf extraction
