### ISSUE TITLE
Zotfile popups don't disappear consistently

### ISSUE THREAD

**Issue by jlegewie** [jlegewie/zotfile#293] opened 2017-08-09 20:03 UTC

**Comment by titaniumbones** [comment] 2017-08-24 19:32
No description in this issue, but I'm seeing this as well.  When zotfile adds an attachment, the notification popup often remains painted on the screen.  This behaviour doesn't appear to be fully consistent, so I'm not sure how easy it is to reproduce.  I'm running Zotero 5 under GNOME on a pretty-much-up-to-date Arch Linux, but I've had this issue for quite a while, definitely since Zotero 4.

**Comment by titaniumbones** [comment] 2017-08-24 19:33
ah, I see you're the author @jlegewie!

**Comment by titaniumbones** [comment] 2017-09-05 16:34
@jlegewie do you know why this is happening, and can you suggest any workarounds? The bottom-right of my screen becomes unusable after a hsort while whenever I'm adding citations... 😢

**Comment by bwiernik** [comment] 2017-09-05 16:49
You can close the pop-ups by clicking on them until the bug is fixed.

**Comment by titaniumbones** [comment] 2017-09-06 16:58
@bwiernik I'm not able to click on the windows.  My window manager treats them as if they don't exist -- clicks in the popups are interpreted as clicks in the next window down in the window manager stack.  The only application I can get to draw over them is VLC in fullscreen mode. So I think they're not being handled properly at some underlying level.

**Comment by titaniumbones** [comment] 2017-09-06 17:03
@bwiernik ~I'm not able to click on the windows.  My window manager treats them as if they don't exist~

I was about to say I can't click on them, but in fact I can, if I move all windows out of that side of the window manager.  So, thank you so much for the help!

But there is definitely something odd about the way the popups are being drawn. If there are any windows behind the popup, clicks in the popups are interpreted as clicks in the next window down in the window manager stack.  So, for some reason my window manager keeps them visible at all times, even when it seems to think they're "below" the current window for purposes of mouse focus.  The only application I can get to draw over them is VLC in fullscreen mode, but when I switch back to regular mode they are back on top of all other windows again.

Really nice to have the workaround though, thank you!

**Comment by patrickkelso** [comment] 2017-09-16 11:08
I have the same problem on OSX and Fedora 26 with i3.

If you change the extensions.zotfile.info_window_duration & extensions.zotfile.info_window_duration_clickable values from the default of 8000 to 0 the popups vanish immediately. I changed my settings to 5000 and they now vanish in 5 seconds. Not sure why it is apparently ignoring the default setting.

http://zotfile.com/#hidden-options <== instructions for editing config.

**Comment by jGleitz** [comment] 2017-09-28 14:37
I’m affected by this, too. However, I can never click on the popups, no matter whether there are windows below them or not. So it seems that I have no way to get rid of them.

**Comment by alexmitrani** [comment] 2017-11-08 20:40
I'm getting the same problem.  The popups do disappear when I click on them but I am transferring about 2000 files from Mendeley to Zotero so this is not a practical workaround, it is like bang-a-mole.  I'm using Windows 7, 64-bit operating system.  Please let me know if you need any further information.  I'm not sure where to check the Zotfile version but I installed it recently, in the last 2 weeks.  I'm using Zotero 5.0.24.  Thanks.

**Comment by jlegewie** [comment] 2017-11-11 13:55
For me this problem disappeared in the latest Zotero beta (5.0.25-beta.3). Can anyone confirm this? If the problem still exists for you, can you provide steps to reproduce?

**Comment by bwiernik** [comment] 2017-11-11 14:01
Seems to be fixed for me, too. (5.0.25-beta.5+fbf2fbe0c)

**Closed** 2017-11-11 14:36 UTC

**Comment by bwiernik** [comment] 2017-11-13 09:15
Actually, it's fixed when the "Rename Attachments" context menu option is used, but not when an attachment is automatically renamed when it is added to an item. In the second case, the popup still persists until clicked.

**Comment by ookimi** [comment] 2017-11-13 16:10
I also had this bug on Ubuntu for auto-renamed files. Just installed the dev version, now it works. (zotero 5.0.24+155c3a4)

**Comment by jlegewie** [comment] 2017-11-15 01:26
Thanks. Just released the version with the fix.
